FROM golang:alpine as builder
RUN apk update && apk upgrade && apk add --no-cache git

RUN go get github.com/mholt/caddy/caddy \
    && go get github.com/caddyserver/builds \
    && cd $GOPATH/src/github.com/mholt/caddy/caddy \
    && sed -i 's/var EnableTelemetry = true/var EnableTelemetry = false/' caddymain/run.go \
    && go run build.go

FROM alpine
RUN apk update && apk upgrade && apk add --no-cache ca-certificates
COPY --from=builder /go/src/github.com/mholt/caddy/caddy/caddy /srv/caddy
COPY Caddyfile /srv/Caddyfile

EXPOSE 80
EXPOSE 443

WORKDIR /srv
CMD ["/srv/caddy", "-agree=true", "-log=stdout"]
