FROM golang:alpine as builder
RUN apk update && apk upgrade && apk add --no-cache git
RUN mkdir /build
COPY . /build/
WORKDIR /build
RUN go build -o upngo .

FROM alpine
COPY --from=builder /build/upngo /upngo

EXPOSE 8080

CMD ["/upngo"]
